schema: "classroom50/repo-config/v1"
classroom: "herramientas-26"
assignment: "introduccion-a-git"
owner:
  username: "adrianortiz2811"
  id: 323597635
  accepted_at: "2026-09-02T22:59:18Z"
source:
  owner: "TDHclassroom"
  owner_id: 219900396
  repo: "git-basic"
  branch: "main"
